### ISSUE TITLE
Cannot use Enhanced-Nextion-Library as-is from Arduino IDE

### ISSUE THREAD

**Issue by avillacis** [jyberg/Enhanced-Nextion-Library#19]
When trying to use this fork of ITEADLIB_Arduino_Nextion, Arduino IDE fails to recognize this library as valid. No examples are provided, and any compilation fails because Nextion.h is not found.

When starting Arduino IDE from the command line, the following line is logged several times:

`Invalid library found in /home/alex/Arduino/libraries/ITEADLIB_Arduino_Nextion-master: no headers files (.h) found in /home/alex/Arduino/libraries/ITEADLIB_Arduino_Nextion-master/src
`

**Comment by jyberg** [comment]
Arduino example projects are under example folder. Source files .cpp are locate in .\src\ folder and header files .h are located in the .\include\ folder. Arduino ide has limited functionality and  it requires that header and source files are under same folder. So you have two options: Recommended change editor some professional editor e.g Visual Studio Code with PlatformIO extension. Or re-locate header and cpp files so that they are in same folder under library folder.
