### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by eyithings** [jyberg/Enhanced-Nextion-Library#25]
Hi, I'm making plans to port your library to another platform. I need to write a display driver for OpenWRT. **Could you point me to the parts of your library that are platform-independent?** For example, the src folder looks like something I can build upon. I am asking about parts of the library that would serve as the starting point, parts that are free of anything Arduino.

Thank you for the work you put into this library.

**Comment by jyberg** [comment]
hi,
From portability point of vew I see only issue that you need replace serial/software serial communication basiaclly implement needed wrapper for serial communication for nexSerial in nexHardware, or re-implememt nexhardware for other board. The issue can be that OpenWRT seems to reguire some type of wrapper/emulator for serial communication? I'm not familar woth OpenWRT boards connectivity/functionality... hope this helps... And if you sucseea so that OpenWrt interface support can be behind of compiler flag with out huge modification to the otjer functionality I hope that we can merge changes here so that library comes more usable for other boarda also...

**Comment by eyithings** [comment]
Hi,

This is now at github.com/EyitopeIO/Arduino-Onion. I'm yet to do the licensing and acknowledgment stuff, but I'm already set to use the ported code. 

A makefile exists in the repo. Because it's a Linux interface, few Arduino names were not compatible. For example, YourSerial.read( )/write( ) had to be renamed to YourSerial.o_read( )/o_write( ) since Linux uses those names as standard functions.

I am yet to build my application on top of this library. but at least basic functionality works. I can accept queued events from Nextion, however, callback functions don't seem to be called. Callbacks are defined and registered in main.cpp if you wish to have a look.

I will revisit this again soon.

**Comment by jyberg** [comment]
hi,

I checked it... Have you thing to implament chagnes so that Onion and other arduino/esp boards are all compatible using #ifdefs?
also why you have implemented min, max, utoa, itoa functions as they are available in base C++ / std library. also yield can be found from std or directy from linux
